build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: make install-dev-tools && make run-phpunit ARGS="--coverage-clover coverage/clover.xml"
                        coverage:
                            file: coverage/clover.xml
                            format: clover
            environment:
                php:
                    version: 7.4
