build:
    cache:
        directories:
            - vendor        # Cache for already installed composer package -> speed up composer install
            - bin           # As vendor directory is cached, bin directory must be also cached (as some dependency will not installed if they are already present and so, related binary will not be linked)
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
    nodes:
        analysis:
            environment:
                php:
                    version: 8.2
                variables:
                    XDEBUG_MODE: 'coverage'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: make install-dev-tools && make run-phpunit ARGS="--migrate-configuration" && make run-phpunit ARGS="--exclude-group memory-heavy --coverage-clover coverage/clover.xml"
                        coverage:
                            file: coverage/clover.xml
                            format: clover
